version: '3.8'

services:
      
  redis:
    image: 'bitnami/redis:latest'
    container_name: 'redis'
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./redis.conf:/opt/bitnami/redis/etc/redis.conf
    command: [ "redis-server", "/opt/bitnami/redis/etc/redis.conf" ]
    networks:
      - net

networks:
  net:
    driver: bridge
